import './globals.css'

export const metadata = {
  title: 'Panaverse DAO',
  description: 'Generated by RanaVerse',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-[#000000]">{children}</body>
    </html>
  )
}
